FROM registry.svc.ci.openshift.org/openshift/release:rhel-8-release-openshift-4.6 AS build

RUN mkdir /build
COPY . /build
RUN mkdir -p /build /build/presto-server/target /build/presto-cli/target

COPY opt_maven_install.sh /tmp/
RUN chmod u+x /tmp/opt_maven_install.sh && /tmp/opt_maven_install.sh $OPENSHIFT_CI

RUN find /build -name '*.jar'

